@startuml
' syntax: 
' https://plantuml.com/class-diagram

class Pawn 

class Board 

class Cell
Cell --* Board

interface Player 

class HumanPlayer implements Player

class AiPlayer implements Player



interface Memento {

}

class Snaphot implements Memento {
    
    --
    _MetaData_
    getName()
    getSnapshotDate()
}

class Board {
    makeSnapshot() : Snaphot
    restore(Snaphot)
}

Interface RuleSet

class ClassicCheckers implements RuleSet

class PapyCheckers implements RuleSet

GameMaster --> RuleSet : "rules"
GameMaster --> Player : "current_player"
GameMaster --> Board : "board"

Player "1" -- "*" Pawn
Cell -- Pawn


RuleSet --> Move : creates
class Move {
    DoMove(Board) : void
    UndoMove(Board) : void
}


@enduml